from __future__ import annotations

from pathlib import Path
from typing import List

import numpy as np
import pandas as pd
import scanpy as sc
import scipy.sparse as sp
from anndata import AnnData


def load_training_gene_order(hvg_csv_path: str | Path) -> List[str]:
    """
    Load the exact training gene order from the CSV generated by save_hvg_list().

    Expected columns:
    - gene_order
    - ensembl_id
    - gene_symbol
    """
    hvg_csv_path = Path(hvg_csv_path)
    df = pd.read_csv(hvg_csv_path)

    required_cols = {"gene_order", "ensembl_id"}
    missing_cols = required_cols - set(df.columns)
    if missing_cols:
        raise ValueError(
            f"Missing required columns in HVG CSV: {missing_cols}. "
            f"Found columns: {list(df.columns)}"
        )

    df = df.sort_values("gene_order").reset_index(drop=True)
    gene_order = df["ensembl_id"].astype(str).tolist()

    if len(gene_order) == 0:
        raise ValueError("Training gene order is empty.")

    if len(gene_order) != len(set(gene_order)):
        raise ValueError("Training gene order contains duplicate Ensembl IDs.")

    return gene_order


def align_genes_to_training(
    adata: AnnData,
    training_gene_order: List[str],
    copy: bool = True,
) -> AnnData:
    """
    Align inference data to the exact training gene set and order.

    Rules:
    - match genes using Ensembl IDs in adata.var_names
    - reorder genes according to training_gene_order
    - fill missing training genes with zeros
    - remove extra genes not used during training
    """
    if copy:
        adata = adata.copy()

    if adata.var_names.has_duplicates:
        raise ValueError(
            "adata.var_names contains duplicate gene IDs. "
            "Expected unique Ensembl IDs."
        )

    input_genes = adata.var_names.astype(str).tolist()
    input_gene_to_idx = {gene: idx for idx, gene in enumerate(input_genes)}

    matched_genes = [g for g in training_gene_order if g in input_gene_to_idx]
    missing_genes = [g for g in training_gene_order if g not in input_gene_to_idx]
    extra_genes = [g for g in input_genes if g not in set(training_gene_order)]

    X = adata.X
    is_sparse = sp.issparse(X)

    aligned_columns = []
    aligned_var_rows = []

    for gene in training_gene_order:
        if gene in input_gene_to_idx:
            idx = input_gene_to_idx[gene]
            aligned_columns.append(X[:, idx])

            var_row = adata.var.iloc[[idx]].copy()
            var_row.index = [gene]
            var_row["filled_missing_during_alignment"] = False
            aligned_var_rows.append(var_row)
        else:
            if is_sparse:
                zero_col = sp.csr_matrix((adata.n_obs, 1), dtype=X.dtype)
            else:
                zero_col = np.zeros((adata.n_obs, 1), dtype=X.dtype)

            aligned_columns.append(zero_col)

            zero_var = pd.DataFrame(index=[gene])
            zero_var["filled_missing_during_alignment"] = True
            aligned_var_rows.append(zero_var)

    if is_sparse:
        X_aligned = sp.hstack(aligned_columns, format="csr")
    else:
        X_aligned = np.hstack(aligned_columns)

    var_aligned = pd.concat(aligned_var_rows, axis=0)
    var_aligned.index = training_gene_order

    adata_aligned = AnnData(
        X=X_aligned,
        obs=adata.obs.copy(),
        var=var_aligned,
        uns=adata.uns.copy(),
    )

    adata_aligned.var_names = training_gene_order

    adata_aligned.uns["gene_alignment"] = {
        "gene_id_type": "Ensembl ID",
        "n_input_genes": int(len(input_genes)),
        "n_training_genes": int(len(training_gene_order)),
        "n_matched_genes": int(len(matched_genes)),
        "n_missing_genes_filled_with_zero": int(len(missing_genes)),
        "n_extra_genes_removed": int(len(extra_genes)),
        "alignment_rule": "match_by_ensembl_reorder_fill_missing_with_zero_remove_extra",
    }

    print("Gene alignment summary:")
    print(f"- Input genes: {len(input_genes)}")
    print(f"- Training genes: {len(training_gene_order)}")
    print(f"- Matched genes: {len(matched_genes)}")
    print(f"- Missing genes filled with zero: {len(missing_genes)}")
    print(f"- Extra genes removed: {len(extra_genes)}")

    return adata_aligned


if __name__ == "__main__":
    input_path = Path("outputs/pbmc68k_preprocessed_for_inference.h5ad")
    hvg_csv_path = Path("outputs/pbmc68k_hvg_list.csv")
    output_path = Path("outputs/pbmc68k_aligned_for_inference.h5ad")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    adata = sc.read_h5ad(input_path)
    training_gene_order = load_training_gene_order(hvg_csv_path)

    adata_aligned = align_genes_to_training(
        adata=adata,
        training_gene_order=training_gene_order,
    )

    adata_aligned.write(output_path)

    print("Gene alignment finished successfully.")
    print(adata_aligned)
    print(f"Saved aligned inference dataset to: {output_path}")